export const ADD_SLOT = "ADD_SLOT";
export const FETCH_AVAILABLE_SLOTS = "FETCH_AVAILABLE_SLOTS";
export const FETCH_AVAILABLE_SLOTS_LOADING = "FETCH_AVAILABLE_SLOTS_LOADING";
export const FETCH_AVAILABLE_SLOTS_ERROR = "FETCH_AVAILABLE_SLOTS_ERROR";
export const CREATE_SLOTS_LOADING = "CREATE_SLOTS_LOADING";
export const CREATE_SLOTS_ERROR = " CREATE_SLOTS_ERROR";
